# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        pre-trained model: 1
        T5: 1
        mT5: 1
        natural language processing: 1
        named entity recognition: 1
     
# 通知の閾値
score_threshold: 0
